/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pacientes/{idPaciente}/obrasocial/credenciales/{idCredencial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["editarCredencialRecepcionista"];
        post?: never;
        delete: operations["eliminarCredencialRecepcionista"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/obrasocial/credenciales/{idCredencial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["editarCredencialPaciente"];
        post?: never;
        delete: operations["eliminarCredencialPaciente"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/consultas/{consultaId}/revision-prioridad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["revisarPrioridad"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/hospitales/{hospitalId}/membresias/{membresiaId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["actualizarRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recepcion/sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["iniciarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recepcion/sesiones/{sesionId}/cerrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cerrarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recepcion/admisiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarAdmisionesAbiertas"];
        put?: never;
        post: operations["crearAdmision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recepcion/admisiones/{admisionId}/finalizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finalizar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recepcion/admisiones/{admisionId}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/hospitales/{hospitalId}/primer-admin/invitaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["primerAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{idPaciente}/obrasocial/credencial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cargarCredencialRecepcionista"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paciente/consulta/sigo-asistiendo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sigoAsistiendo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paciente/consulta/llegue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["llegue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paciente/consulta/estoy-atrasado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["estoyAtrasado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paciente/consulta/ausentarme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ausentarme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/obrasocial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cargarObraSocialAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/obrasocial/credenciales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerCredencialesPaciente"];
        put?: never;
        post: operations["cargarCredencialPaciente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["iniciarSesion_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/reanudar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reanudarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/pausar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pausarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/llamar-proximo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["llamarProximo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/consultas/{consultaId}/presente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmarPresente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/consultas/{consultaId}/finalizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finalizarConsulta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/consultas/{consultaId}/ausente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["marcarAusente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/cerrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cerrarSesion_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitaciones/{token}/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitaciones/{token}/aceptar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["aceptar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["iniciarChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{id}/mensajes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enviarMensaje"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atencion/hospital": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["seleccionarHospital"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/hospitales/{hospitalId}/invitaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invitaciones"];
        put?: never;
        post: operations["invitar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/hospitales/{hospitalId}/membresias/{membresiaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["actualizarEstado"];
        trace?: never;
    };
    "/api/staff/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recepcion/sesiones/activa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sesionActiva"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recepcion/pacientes/{dni}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["buscarPaciente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recepcion/hospitales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["hospitales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recepcion/admisiones/{admisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerAdmision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{idPaciente}/obrasocial/credenciales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerCredencialesPacienteRecepcionista"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paciente/consulta/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerEstado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/pacientes-disponibles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarPacientesDisponibles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/{sesionId}/consultas/{consultaId}/pretriaje": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerPretriaje"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/sesiones/actual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerSesionActual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/pacientes/{pacienteId}/ultimos-reportes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerHistorialClinicoMasActuales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/pacientes/{pacienteId}/historial-clinico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerHistorialClinico"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/pacientes/{pacienteId}/historial-clinico/{estudioId}/reporte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerMetadataDeUnEstudioClinico"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/pacientes/{pacienteId}/historial-clinico/{estudioId}/archivo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["descargarArchivoEstudioClinico"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/atenciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerHistorial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medico/asignaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerAsignaciones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitaciones/{token}/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resumen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hospitales/{hospitalId}/salas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerSalas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hospitales/cercanos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerHospitalesCercanos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/especialidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerEspecialidades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChatActual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atencion/tiempos/suscribirse/{consultaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["suscribirse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atencion/tiempo-estimado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["obtenerTiempoEstimadoDeAtencion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/hospitales/{hospitalId}/personal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["personal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/hospitales/{hospitalId}/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auditoria"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/obrasocial/{idObraSocial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["eliminarObraSocialAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/hospitales/{hospitalId}/invitaciones/{invitacionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revocar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CredencialRequest: {
            nombreObraSocial: string;
            numeroAfiliado: string;
            plan: string;
            /** Format: date */
            fechaVencimiento: string;
        };
        RevisionPrioridadRequest: {
            /** @enum {string} */
            decision: "CONFIRMAR" | "CORREGIR";
            /** @enum {string} */
            prioridad?: "RIESGO_VITAL_INMEDIATO" | "MUY_URGENTE" | "URGENTE" | "NORMAL" | "NO_URGENTE";
            motivo?: string;
        };
        PretriajeConsultaDTO: {
            /** Format: int64 */
            consultaId?: number;
            /** @enum {string} */
            prioridadPreliminar?: "RIESGO_VITAL_INMEDIATO" | "MUY_URGENTE" | "URGENTE" | "NORMAL" | "NO_URGENTE";
            /** @enum {string} */
            prioridadEfectiva?: "RIESGO_VITAL_INMEDIATO" | "MUY_URGENTE" | "URGENTE" | "NORMAL" | "NO_URGENTE";
            /** @enum {string} */
            estadoRevision?: "PENDIENTE" | "CONFIRMADA" | "CORREGIDA";
            resumenClinico?: components["schemas"]["TriageResultDTO"];
            revisionActual?: components["schemas"]["RevisionPrioridadDTO"];
        };
        RevisionPrioridadDTO: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            decision?: "CONFIRMAR" | "CORREGIR";
            /** @enum {string} */
            prioridadAnterior?: "RIESGO_VITAL_INMEDIATO" | "MUY_URGENTE" | "URGENTE" | "NORMAL" | "NO_URGENTE";
            /** @enum {string} */
            prioridadNueva?: "RIESGO_VITAL_INMEDIATO" | "MUY_URGENTE" | "URGENTE" | "NORMAL" | "NO_URGENTE";
            motivo?: string;
            /** Format: date-time */
            fechaHora?: string;
        };
        TriageResultDTO: {
            motivoConsulta?: string;
            sintomas?: string[];
            inicio?: string;
            evolucion?: string;
            /** Format: int32 */
            intensidadDolor?: number;
            signosAlarma?: string[];
            antecedentesRelevantes?: string[];
            medicamentos?: string[];
            alergias?: string[];
            posibilidadEmbarazo?: string;
            observaciones?: string;
            /** Format: int32 */
            nivelPrioridad?: number;
            requiereAtencionInmediata?: boolean;
            recomendacionSeguridad?: string;
        };
        ActualizarRolesRequest: {
            roles: ("ADMIN_HOSPITAL" | "COORDINADOR_MEDICO" | "MEDICO" | "RECEPCIONISTA")[];
        };
        MembresiaResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            hospitalId?: number;
            hospitalNombre?: string;
            /** @enum {string} */
            estado?: "INVITADA" | "ACTIVA" | "SUSPENDIDA" | "REVOCADA";
            roles?: ("ADMIN_HOSPITAL" | "COORDINADOR_MEDICO" | "MEDICO" | "RECEPCIONISTA")[];
        };
        RegisterRequest: {
            nombre: string;
            apellido: string;
            numeroDocumento: string;
            /** @enum {string} */
            tipoDocumento: "LIBRETA_CIVICA" | "LIBRETA_ENROLAMIENTO" | "DNI";
            /** @enum {string} */
            tipoUsuario?: "Medico" | "Recepcionista" | "Paciente";
            matricula?: string;
            /** Format: email */
            email?: string;
            password: string;
            /** @enum {string} */
            rol: "ADMIN" | "USER";
        };
        IniciarSesionRecepcionRequest: {
            /** Format: int64 */
            hospitalId: number;
        };
        SesionRecepcionDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            hospitalId?: number;
            hospitalNombre?: string;
            /** @enum {string} */
            estado?: "ACTIVA" | "FINALIZADA";
            /** Format: date-time */
            fechaHoraInicio?: string;
            /** Format: date-time */
            fechaHoraFin?: string;
        };
        CrearAdmisionRecepcionRequest: {
            /** Format: int64 */
            sesionId: number;
            dni: string;
            nombre: string;
            apellido: string;
            /** Format: date */
            fechaNacimiento: string;
            /** @enum {string} */
            generoBiologico: "MASCULINO" | "FEMENINO" | "X";
            telefono: string;
            /** Format: email */
            correoElectronico?: string;
            calle: string;
            alturaDomicilio: string;
            piso?: string;
            ciudad: string;
            provincia: string;
            codigoPostal: string;
            codigoEspecialidad: string;
        };
        AdmisionRecepcionDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            consultaId?: number;
            /** Format: int64 */
            pacienteId?: number;
            codigoLlamado?: string;
            /** @enum {string} */
            estado?: "INICIADA" | "FORMULARIO_COMPLETO" | "FINALIZADA" | "CANCELADA";
            /** @enum {string} */
            prioridad?: "RIESGO_VITAL_INMEDIATO" | "MUY_URGENTE" | "URGENTE" | "NORMAL" | "NO_URGENTE";
            estimacion?: components["schemas"]["TiempoEstimadoAtencionResponse"];
        };
        TiempoEstimadoAtencionResponse: {
            /** Format: int64 */
            consultaId?: number;
            /** Format: date-time */
            fechaHoraAtencionEstimada?: string;
            /** Format: date-time */
            fechaHoraAtencionEstimadaDesde?: string;
            /** Format: date-time */
            fechaHoraAtencionEstimadaHasta?: string;
            hayMedicosActivos?: boolean;
            /** Format: int32 */
            medicosActivos?: number;
            /** Format: int32 */
            medicosParaEstimacion?: number;
            /** Format: int32 */
            posicionEnCola?: number;
            /** Format: int32 */
            pacientesAntes?: number;
            /** Format: int32 */
            minutosPromedioAtencion?: number;
            mensaje?: string;
        };
        DolorReportadoRequest: {
            localizacion: string;
            /** Format: int32 */
            intensidad: number;
        };
        FormularioTriageRecepcionRequest: {
            motivoConsulta: string;
            sintomas: string[];
            inicio: string;
            evolucion: string;
            dolores: components["schemas"]["DolorReportadoRequest"][];
            fiebre?: boolean;
            signosAlarma?: string[];
            antecedentesRelevantes?: string[];
            medicamentos?: string[];
            alergias?: string[];
            posibilidadEmbarazo?: string;
            observaciones?: string;
        };
        AdmisionRecepcionDetalleDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            consultaId?: number;
            /** Format: int64 */
            sesionId?: number;
            /** Format: int64 */
            pacienteId?: number;
            pacienteDni?: string;
            pacienteNombre?: string;
            pacienteApellido?: string;
            /** Format: int64 */
            hospitalId?: number;
            hospitalNombre?: string;
            especialidadCodigo?: string;
            especialidadNombre?: string;
            codigoLlamado?: string;
            /** @enum {string} */
            estado?: "INICIADA" | "FORMULARIO_COMPLETO" | "FINALIZADA" | "CANCELADA";
            /** @enum {string} */
            prioridad?: "RIESGO_VITAL_INMEDIATO" | "MUY_URGENTE" | "URGENTE" | "NORMAL" | "NO_URGENTE";
            /** Format: date-time */
            fechaHoraInicio?: string;
            /** Format: date-time */
            fechaHoraFinalizacion?: string;
            /** Format: date-time */
            fechaHoraCancelacion?: string;
            estimacion?: components["schemas"]["TiempoEstimadoAtencionResponse"];
        };
        CrearInvitacionRequest: {
            /** Format: email */
            email: string;
            roles: ("ADMIN_HOSPITAL" | "COORDINADOR_MEDICO" | "MEDICO" | "RECEPCIONISTA")[];
            matricula?: string;
            /** @enum {string} */
            tipoMatricula?: "NACIONAL" | "PROVINCIAL";
            jurisdiccionMatricula?: string;
            especialidadIds?: number[];
        };
        InvitacionResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            hospitalId?: number;
            hospitalNombre?: string;
            email?: string;
            /** @enum {string} */
            estado?: "PENDIENTE" | "ACEPTADA" | "EXPIRADA" | "REVOCADA";
            roles?: ("ADMIN_HOSPITAL" | "COORDINADOR_MEDICO" | "MEDICO" | "RECEPCIONISTA")[];
            especialidadIds?: number[];
            matricula?: string;
            /** @enum {string} */
            tipoMatricula?: "NACIONAL" | "PROVINCIAL";
            jurisdiccionMatricula?: string;
            /** Format: date-time */
            venceEn?: string;
            /** Format: date-time */
            fechaCreacion?: string;
            emailEnviado?: boolean;
            tokenEntregaUnica?: string;
        };
        EstadoConsultaPacienteDTO: {
            /** Format: int64 */
            consultaId?: number;
            /** @enum {string} */
            estadoConsulta?: "PENDIENTE" | "HOSPITAL_SELECCIONADO" | "PRETRIAGE_FINALIZADO" | "PRETRIAGE_EN_PROCESO" | "EN_COLA" | "LLAMADO" | "EN_ESPERA" | "ATRASADO" | "EN_ATENCION" | "FINALIZADA" | "CANCELADA";
            /** @enum {string} */
            estadoEntradaCola?: "EN_COLA" | "LLAMADO" | "EN_ESPERA" | "ATRASADO" | "EN_ATENCION" | "FINALIZADA" | "CANCELADA";
            /** @enum {string} */
            tipoPausa?: "AUSENTE_AL_LLAMADO" | "ESPERA_MANUAL" | "ATRASADO_CONFIRMADO";
            /** Format: date-time */
            fechaHoraLimiteRespuesta?: string;
            tiempoEstimadoAtencion?: components["schemas"]["TiempoEstimadoAtencionResponse"];
        };
        ObraSocialDTO: {
            nombre: string;
        };
        Coordenada: {
            /** Format: int64 */
            id?: number;
            /** Format: double */
            latitud?: number;
            /** Format: double */
            longitud?: number;
        };
        Credencial: {
            /** Format: int64 */
            id?: number;
            numeroAfiliado?: string;
            plan?: string;
            /** Format: date */
            fechaVencimiento?: string;
            obraSocial?: components["schemas"]["ObraSocial"];
            paciente?: components["schemas"]["Paciente"];
        };
        Direccion: {
            /** Format: int64 */
            id?: number;
            calle?: string;
            altura?: string;
            piso?: string;
            codigoPostal?: string;
            ciudad?: string;
            provincia?: string;
            coordenada?: components["schemas"]["Coordenada"];
        };
        EstudioClinico: {
            /** Format: int64 */
            id?: number;
            paciente?: unknown;
            nombreArchivo?: string;
            tipoArchivo?: string;
            extensionArchivo?: string;
            descripcion?: string;
            /** Format: date-time */
            fechaSubida?: string;
            /** Format: int64 */
            tamanoArchivo?: number;
            rutaArchivo?: string;
        };
        ObraSocial: {
            /** Format: int64 */
            id?: number;
            nombre?: string;
            credenciales?: components["schemas"]["Credencial"][];
            virgente?: boolean;
        };
        Paciente: {
            /** Format: int64 */
            id?: number;
            usuarioAuth?: components["schemas"]["UsuarioAuth"];
            credenciales?: components["schemas"]["Credencial"][];
            coordenadaActual?: components["schemas"]["Coordenada"];
            historialClinico?: components["schemas"]["EstudioClinico"][];
            /** @enum {string} */
            generoBiologico?: "MASCULINO" | "FEMENINO" | "X";
            /** @enum {string} */
            generoConElQueSeIdentifica?: "MASCULINO" | "FEMENINO" | "X";
            nombre?: string;
            apellido?: string;
            numeroDocumento?: string;
            /** @enum {string} */
            tipoDocumento?: "LIBRETA_CIVICA" | "LIBRETA_ENROLAMIENTO" | "DNI";
            /** @enum {string} */
            origenRegistro?: "APLICACION" | "RECEPCION";
            /** Format: date */
            fechaNacimiento?: string;
            telefono?: string;
            correoElectronico?: string;
            direccion?: components["schemas"]["Direccion"];
            /** Format: double */
            peso?: number;
            /** Format: int32 */
            altura?: number;
        };
        UsuarioAuth: {
            id?: string;
            nombre?: string;
            apellido?: string;
            numeroDocumento?: string;
            /** @enum {string} */
            tipoDocumento?: "LIBRETA_CIVICA" | "LIBRETA_ENROLAMIENTO" | "DNI";
            correoElectronico?: string;
            /** @enum {string} */
            rol?: "ADMIN" | "USER";
        };
        IniciarSesionMedicaRequest: {
            /** Format: int64 */
            hospitalId: number;
            codigoEspecialidad: string;
            /** Format: int64 */
            salaId: number;
        };
        SesionAtencionMedicaDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            hospitalId?: number;
            codigoEspecialidad?: string;
            /** Format: int64 */
            salaId?: number;
            /** @enum {string} */
            estado?: "ACTIVA" | "PAUSADA" | "FINALIZADA";
        };
        ConsultaLlamadaDTO: {
            /** Format: int64 */
            consultaId?: number;
            codigoLlamado?: string;
            /** Format: int64 */
            pacienteId?: number;
            nombrePaciente?: string;
            apellidoPaciente?: string;
            /** Format: int64 */
            salaId?: number;
            nombreSala?: string;
            /** @enum {string} */
            prioridad?: "RIESGO_VITAL_INMEDIATO" | "MUY_URGENTE" | "URGENTE" | "NORMAL" | "NO_URGENTE";
            /** @enum {string} */
            estadoConsulta?: "PENDIENTE" | "HOSPITAL_SELECCIONADO" | "PRETRIAGE_FINALIZADO" | "PRETRIAGE_EN_PROCESO" | "EN_COLA" | "LLAMADO" | "EN_ESPERA" | "ATRASADO" | "EN_ATENCION" | "FINALIZADA" | "CANCELADA";
        };
        LoginRequest: {
            /** Format: email */
            email?: string;
            password: string;
        };
        RegistrarInvitadoRequest: {
            nombre: string;
            apellido: string;
            numeroDocumento: string;
            /** @enum {string} */
            tipoDocumento: "LIBRETA_CIVICA" | "LIBRETA_ENROLAMIENTO" | "DNI";
            password: string;
        };
        ChatDTO: {
            /** Format: int64 */
            id?: number;
            mensajes?: components["schemas"]["MensajeDTO"][];
            /** Format: date-time */
            timestamp?: string;
            finalizado?: boolean;
        };
        MensajeDTO: {
            contenido?: string;
            autor?: string;
            /** Format: date-time */
            fechaHoraEnvio?: string;
        };
        EnviarMensajeRequest: {
            contenido: string;
        };
        ChatTurnResponse: {
            respuesta?: components["schemas"]["MensajeDTO"];
            atencionEstimada?: components["schemas"]["TiempoEstimadoAtencionResponse"];
        };
        SeleccionHospitalRequest: {
            placeId: string;
            codigoEspecialidad: string;
        };
        ActualizarMembresiaRequest: {
            /** @enum {string} */
            estado: "INVITADA" | "ACTIVA" | "SUSPENDIDA" | "REVOCADA";
        };
        StaffMeResponse: {
            id?: string;
            nombre?: string;
            apellido?: string;
            email?: string;
            administradorPlataforma?: boolean;
            membresias?: components["schemas"]["MembresiaResponse"][];
        };
        PacienteRecepcionDTO: {
            /** Format: int64 */
            id?: number;
            dni?: string;
            nombre?: string;
            apellido?: string;
            /** Format: date */
            fechaNacimiento?: string;
            /** @enum {string} */
            generoBiologico?: "MASCULINO" | "FEMENINO" | "X";
            telefono?: string;
            correoElectronico?: string;
            calle?: string;
            alturaDomicilio?: string;
            piso?: string;
            ciudad?: string;
            provincia?: string;
            codigoPostal?: string;
            registradoEnAplicacion?: boolean;
            atencionEnCurso?: boolean;
            /** @enum {string} */
            estadoAtencionEnCurso?: "PENDIENTE" | "HOSPITAL_SELECCIONADO" | "PRETRIAGE_FINALIZADO" | "PRETRIAGE_EN_PROCESO" | "EN_COLA" | "LLAMADO" | "EN_ESPERA" | "ATRASADO" | "EN_ATENCION" | "FINALIZADA" | "CANCELADA";
        };
        EspecialidadMedicaDTO: {
            codigo?: string;
            nombre?: string;
        };
        RecepcionHospitalDTO: {
            /** Format: int64 */
            id?: number;
            nombre?: string;
            especialidades?: components["schemas"]["EspecialidadMedicaDTO"][];
        };
        CredencialResponse: {
            /** Format: int64 */
            id?: number;
            numeroAfiliado?: string;
            plan?: string;
            /** Format: date */
            fechaVencimiento?: string;
        };
        SesionMedicaActualDTO: {
            sesion?: components["schemas"]["SesionAtencionMedicaDTO"];
            consultaActual?: components["schemas"]["ConsultaLlamadaDTO"];
        };
        EstudioClinicoDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            pacienteId?: number;
            nombreArchivo?: string;
            tipoArchivo?: string;
            extensionArchivo?: string;
            descripcion?: string;
            /** Format: date-time */
            fechaSubida?: string;
            /** Format: int64 */
            tamanoArchivo?: number;
            rutaArchivo?: string;
        };
        AtencionMedicaDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            consultaId?: number;
            /** Format: int64 */
            sesionId?: number;
            /** Format: int64 */
            pacienteId?: number;
            /** Format: int64 */
            hospitalId?: number;
            codigoEspecialidad?: string;
            /** Format: int64 */
            salaId?: number;
            /** @enum {string} */
            estado?: "EN_CURSO" | "FINALIZADA";
            /** Format: date-time */
            fechaHoraInicio?: string;
            /** Format: date-time */
            fechaHoraFin?: string;
        };
        AsignacionMedicoDTO: {
            /** Format: int64 */
            hospitalId?: number;
            nombreHospital?: string;
            codigoEspecialidad?: string;
            nombreEspecialidad?: string;
        };
        InvitacionResumenResponse: {
            /** Format: int64 */
            hospitalId?: number;
            hospitalNombre?: string;
            email?: string;
            /** @enum {string} */
            estado?: "PENDIENTE" | "ACEPTADA" | "EXPIRADA" | "REVOCADA";
            roles?: ("ADMIN_HOSPITAL" | "COORDINADOR_MEDICO" | "MEDICO" | "RECEPCIONISTA")[];
            especialidadIds?: number[];
            matricula?: string;
            /** @enum {string} */
            tipoMatricula?: "NACIONAL" | "PROVINCIAL";
            jurisdiccionMatricula?: string;
            /** Format: date-time */
            venceEn?: string;
            cuentaExistente?: boolean;
        };
        SalaDTO: {
            /** Format: int64 */
            id?: number;
            nombre?: string;
        };
        HospitalCercanoDTO: {
            placeId?: string;
            nombre?: string;
            direccion?: string;
            especialidades?: components["schemas"]["EspecialidadMedicaDTO"][];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        PersonalResponse: {
            /** Format: int64 */
            membresiaId?: number;
            nombre?: string;
            apellido?: string;
            email?: string;
            /** @enum {string} */
            estado?: "INVITADA" | "ACTIVA" | "SUSPENDIDA" | "REVOCADA";
            roles?: ("ADMIN_HOSPITAL" | "COORDINADOR_MEDICO" | "MEDICO" | "RECEPCIONISTA")[];
        };
        AuditoriaResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            fecha?: string;
            actor?: string;
            accion?: string;
            objetivo?: string;
            resultado?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    editarCredencialRecepcionista: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idPaciente: number;
                idCredencial: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    eliminarCredencialRecepcionista: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idPaciente: number;
                idCredencial: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    editarCredencialPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idCredencial: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    eliminarCredencialPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idCredencial: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    revisarPrioridad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
                consultaId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionPrioridadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PretriajeConsultaDTO"];
                };
            };
        };
    };
    actualizarRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospitalId: number;
                membresiaId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarRolesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MembresiaResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    iniciarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IniciarSesionRecepcionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionRecepcionDTO"];
                };
            };
        };
    };
    cerrarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionRecepcionDTO"];
                };
            };
        };
    };
    listarAdmisionesAbiertas: {
        parameters: {
            query: {
                sesionId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdmisionRecepcionDetalleDTO"][];
                };
            };
        };
    };
    crearAdmision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearAdmisionRecepcionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdmisionRecepcionDTO"];
                };
            };
        };
    };
    finalizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                admisionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormularioTriageRecepcionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdmisionRecepcionDTO"];
                };
            };
        };
    };
    cancelar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                admisionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdmisionRecepcionDetalleDTO"];
                };
            };
        };
    };
    primerAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospitalId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearInvitacionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvitacionResponse"];
                };
            };
        };
    };
    cargarCredencialRecepcionista: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idPaciente: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    sigoAsistiendo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EstadoConsultaPacienteDTO"];
                };
            };
        };
    };
    llegue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EstadoConsultaPacienteDTO"];
                };
            };
        };
    };
    estoyAtrasado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EstadoConsultaPacienteDTO"];
                };
            };
        };
    };
    ausentarme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EstadoConsultaPacienteDTO"];
                };
            };
        };
    };
    cargarObraSocialAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObraSocialDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObraSocial"];
                };
            };
        };
    };
    obtenerCredencialesPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CredencialResponse"][];
                };
            };
        };
    };
    cargarCredencialPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    iniciarSesion_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IniciarSesionMedicaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionAtencionMedicaDTO"];
                };
            };
        };
    };
    reanudarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionAtencionMedicaDTO"];
                };
            };
        };
    };
    pausarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionAtencionMedicaDTO"];
                };
            };
        };
    };
    llamarProximo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsultaLlamadaDTO"];
                };
            };
        };
    };
    confirmarPresente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
                consultaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsultaLlamadaDTO"];
                };
            };
        };
    };
    finalizarConsulta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
                consultaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsultaLlamadaDTO"];
                };
            };
        };
    };
    marcarAusente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
                consultaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsultaLlamadaDTO"];
                };
            };
        };
    };
    cerrarSesion_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionAtencionMedicaDTO"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    registrar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarInvitadoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MembresiaResponse"];
                };
            };
        };
    };
    aceptar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MembresiaResponse"];
                };
            };
        };
    };
    iniciarChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatDTO"];
                };
            };
        };
    };
    enviarMensaje: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnviarMensajeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatTurnResponse"];
                };
            };
        };
    };
    seleccionarHospital: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeleccionHospitalRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invitaciones: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospitalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvitacionResponse"][];
                };
            };
        };
    };
    invitar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospitalId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearInvitacionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvitacionResponse"];
                };
            };
        };
    };
    actualizarEstado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospitalId: number;
                membresiaId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarMembresiaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MembresiaResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffMeResponse"];
                };
            };
        };
    };
    sesionActiva: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionRecepcionDTO"];
                };
            };
        };
    };
    buscarPaciente: {
        parameters: {
            query: {
                sesionId: number;
            };
            header?: never;
            path: {
                dni: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PacienteRecepcionDTO"];
                };
            };
        };
    };
    hospitales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecepcionHospitalDTO"][];
                };
            };
        };
    };
    obtenerAdmision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                admisionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdmisionRecepcionDetalleDTO"];
                };
            };
        };
    };
    obtenerCredencialesPacienteRecepcionista: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idPaciente: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CredencialResponse"][];
                };
            };
        };
    };
    obtenerEstado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EstadoConsultaPacienteDTO"];
                };
            };
        };
    };
    listarPacientesDisponibles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsultaLlamadaDTO"][];
                };
            };
        };
    };
    obtenerPretriaje: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesionId: number;
                consultaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PretriajeConsultaDTO"];
                };
            };
        };
    };
    obtenerSesionActual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionMedicaActualDTO"];
                };
            };
        };
    };
    obtenerHistorialClinicoMasActuales: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EstudioClinicoDTO"][];
                };
            };
        };
    };
    obtenerHistorialClinico: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EstudioClinicoDTO"][];
                };
            };
        };
    };
    obtenerMetadataDeUnEstudioClinico: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: number;
                estudioId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EstudioClinicoDTO"];
                };
            };
        };
    };
    descargarArchivoEstudioClinico: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: number;
                estudioId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    obtenerHistorial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AtencionMedicaDTO"][];
                };
            };
        };
    };
    obtenerAsignaciones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AsignacionMedicoDTO"][];
                };
            };
        };
    };
    resumen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvitacionResumenResponse"];
                };
            };
        };
    };
    obtenerSalas: {
        parameters: {
            query: {
                codigoEspecialidad: string;
            };
            header?: never;
            path: {
                hospitalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalaDTO"][];
                };
            };
        };
    };
    obtenerHospitalesCercanos: {
        parameters: {
            query: {
                latitud: number;
                longitud: number;
                codigoEspecialidad: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HospitalCercanoDTO"][];
                };
            };
        };
    };
    obtenerEspecialidades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EspecialidadMedicaDTO"][];
                };
            };
        };
    };
    getChatActual: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChatDTO"];
                };
            };
        };
    };
    suscribirse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consultaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    obtenerTiempoEstimadoDeAtencion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TiempoEstimadoAtencionResponse"];
                };
            };
        };
    };
    personal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospitalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonalResponse"][];
                };
            };
        };
    };
    auditoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospitalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditoriaResponse"][];
                };
            };
        };
    };
    eliminarObraSocialAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idObraSocial: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    revocar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospitalId: number;
                invitacionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
